### ISSUE TITLE
Command 'changeLanguageMode.change' not found

### ISSUE THREAD

**Issue by Kav7** [usernamehw/vscode-commands#10]
hello,

Using the new commands add-in, I get this error when trying to switch languages via this:
`{
        "key": "ctrl+alt+d",
        "command": "changeLanguageMode.change",
        "args": "django-html"
 },`

However, installing the 'deprecated' [change language mode](https://marketplace.visualstudio.com/items?itemName=usernamehw.change-language-mode) add-in, it works again. Is 'commands' meant to have this functionality since its the replacement?

**Comment by usernamehw** [comment]
Command id is different, since extensions usually prefix commands with their name:

```js
{ "key": "ctrl+alt+d", "command": "commands.setEditorLanguage", "args": "django-html" }
```

**Comment by Kav7** [comment]
haha... well that makes sense and it works now, thank you!
