### ISSUE TITLE
command to import from usernamehw.run-commands-view

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#11]
I suggest to:

* create a new `commands.import.run-commands` command
* automatically execute it when `run-commands-view` is setup but `commands` isn't

**Comment by usernamehw** [comment]
I don't think it's worth it. `run-commands-view` had like 1-2k installs? I've already deleted it and it had different config structure.

**Comment by GitMensch** [comment]
Hm, would it be very complicated to add the import command? 1-2k installs is only directly from Marketplace, the additional installations from vsix are not counted, and even for 1k users this seems useful (if it isn't too much work).

**Comment by usernamehw** [comment]
That's the number of installs in a span of several years. There's no number of how many uninstalls there were.

**Comment by GitMensch** [comment]
Hm, feel free to close, I just think "a direct start" would be nice (not sure how much the settings differ and how much adjustments would be needed on the fly). `const oldConfig = workspace.getConfiguration('run-commands-view');` seems to be all that is necessary to read the old settings.

**Comment by usernamehw** [comment]
These 2 extensions have many small differences, it's just not worth it.
