### ISSUE TITLE
add tags for versions

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#12]
Which are automatically shown as releases on GitHub (and provide the _option_ later to run a CI action like uploading to the marketplaces someday).

**Comment by GitMensch** [comment]
@usernamehw Would you apply a script that adds the existing versions as tags (then I'd create a script for that and post it here) and create tags for upcoming versions?
I'd like to subscribe to releases and also be able to get a fast overview of the changes between versions directly on GitHub - tags (or even "full" releases) would help a lot with that.

**Comment by usernamehw** [comment]
I think it was done at some point.

**Comment by GitMensch** [comment]
Rechecked: the last tag available is 1.2.0, maybe you have those all locally and need to only `git push --tags` to send them to this repo?

**Comment by usernamehw** [comment]
Maybe with this it will be synced in the future... `"git.followTagsWhenSync": true,`
