### ISSUE TITLE
run specific task not working?

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#14]
task.json:
```jsonc
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ech o",
            "type": "shell",
            "command": "echo Hello you"
        },
        {
            "label": "clearme",
            "type": "shell",
            "command": "cls"
        }
    ]
}
```

settings.json:
```
    "commands.commands": {
        "▶️ Run Task": {
            "command": "workbench.action.tasks.runTask",
            "args": "ech\\ o"
        },
    },
```

I _think_ this worked that way with run-commands-view before and I know we did document it in its repo (sadly it cannot be found, please make it public again btw), but with this extension and vscode 1.59.1 I always get the prompt which task to execute.

**Comment by usernamehw** [comment]
Why the escape sign? It works without it:

```js
"▶️ Run Task": {
	"command": "workbench.action.tasks.runTask",
	"args": "ech o"
},
```

**Comment by GitMensch** [comment]
I always get the list of commands (no matter if I escape it or not), vscode 1.59.1 here.

**Comment by usernamehw** [comment]
Is it the same if you do that from `keybindings.json` file? This setup works for me:

`tasks.json` (in workspace)

```js
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "ech o",
            "type": "shell",
            "command": "echo Hello you"
        },
        {
            "label": "clearme",
            "type": "shell",
            "command": "cls"
        }
    ]
}
```
`settings.json`

```js
"▶️ Run Task": {
	"command": "workbench.action.tasks.runTask",
	"args": "ech o"
},
```

OS: Windows_NT x64 10.0.19043
Version: 1.59.1 (user setup)

**Comment by GitMensch** [comment]
Hm, the differences I've spotted so far are: system setup codium, user-wide settings.json and tasks.json, other than that: same setup. ... restarted codium, now everything works. Seems like "somehow" the settings.json update was not applied.

Thanks.
