### ISSUE TITLE
commands.startDebugging does not look for launch configurations declared in code-workspace files

### ISSUE THREAD

**Issue by vincent-moral** [usernamehw/vscode-commands#15]
Hello,
I think the title is self-explanatory.
Most of my development environment is located in a file called "myproject.code-workspace".
I have declared a launch configuration called "Launch Debug" into that file.
Then I use the following code to add a command for starting that launch configuration:
`
"Launch Debug": {
    "icon": "run-view-icon",
    "command": "commands.startDebugging",
    "args": "Launch Debug",
    "statusBar": {
        "text": "Launch"
    }
}
`

When I click the command's button I have the following error:
Configuration 'Launch Debug' is missing in "launch.json"

My guess is that the extension looks only for launch configurations located in the launch.json file. It should also look for launch configurations located in the current active code-workspace file.

Let me know if you need more pieces of information regarding this bug.
Anyway, thank you for this great extension !

**Comment by usernamehw** [comment]
I'm kind of not doing anything with that command, just calling the api:

https://github.com/usernamehw/vscode-commands/blob/e02426a7ed79a31a912431fd5999a608a7fe4398/src/commands.ts#L306-L308

Is your workspace multi-root?

**Comment by vincent-moral** [comment]
No, it is not.
I was thinking maybe launch configurations declared in code-workspace files instead of launch.json have different aliases.
In the Run and Debug pannel, my launch configurations are displayed like this:
![image](https://user-images.githubusercontent.com/61452157/131697421-01c97d14-ac79-4061-bf2f-34fd6b6b15dd.png)
You can see there is a "(workspace)" appended to the launch configuration name. I tried to change
`
"args": "Launch Debug"
`
to
`
"arg": "Launch Debug (workspace)"
`
But it did not solve the problem.

**Comment by usernamehw** [comment]
Opened an upstream issue: https://github.com/microsoft/vscode/issues/132058

**Comment by usernamehw** [comment]
@vincent-moral You are using the `"name"` property to launch it, right?

**Comment by vincent-moral** [comment]
Yes, I am

**Comment by usernamehw** [comment]
Closing this since no work is planned.
