### ISSUE TITLE
an option, per item, to disable tooltips

### ISSUE THREAD

**Issue by jimrandell** [usernamehw/vscode-commands#17]
Love this extension so much, i want to take it home AND buy it breakfast the next day!!!

can forgive it almost anything, but must admit this is irritating...would love to turn it off (for some commands, not all):

![image](https://user-images.githubusercontent.com/3543506/142245895-32865ee8-9089-4efb-8f43-48974a4c02ac.png)

**Comment by usernamehw** [comment]
```js
"disableTooltip": true,
```

**Comment by jimrandell** [comment]
Thank you! I wasn't feeling dumb enough today, but this put me over the top. 😯
