### ISSUE TITLE
Run defined command from arg (for use in keybinding)

### ISSUE THREAD

**Issue by zardoy** [usernamehw/vscode-commands#18]
Hi! AFAIU all commands to run must be defined in `commands.commands`, however I want to define them (for example a sequence) in `keybindings.json`.

For example:

```ts
{
    "key": "cmd+r",
    "command": "commands.executeSequence",
    "args": [
        {
            "sequence": ["editor.action.toggleMinimap", "workbench.action.toggleStatusbarVisibility"]
        }
    ]
},
```

Motivation: easier to use in [shared keybindings](https://github.com/zardoy/vscode-keybindings)

**Comment by usernamehw** [comment]
You already can:

```js
{
    "key": "ctrl+shift+9",
    "command": "commands.run",
    "args": [
        "editor.action.toggleMinimap",
        "workbench.action.toggleSidebarVisibility",
    ],
},
```

**Comment by zardoy** [comment]
Oh this command wasn't in manifest, so I didn't see it *Feature Contributions* of VSCode. Also I think it'd good to remove commands and settings from Readme since they're out of sync we have *Feature Contributions* tab in VSCode.

So, missing commands should be added. Also, I created [framework](https://github.com/zardoy/vscode-framework), that allows to use `onCommands` activation event and shows TS errors if you use command that is not in manifest. I hope it would help you a lot, tell WDYT

**Comment by zardoy** [comment]
Anyway, you answered my question so thank you.

**Comment by wdanilo** [comment]
@usernamehw it doesn't work for me. After I added your example to `keybindings.json` and pressing the keys, I've got error:  `command 'commands.run' not found`. Would you be so nice and tell me how to fix it, please? :)

**Comment by zardoy** [comment]
1. Install extension
2. Ensure it gets activated

@usernamehw will this extension support web some day? I understand you have millions of features here that might be hard to adopt, but Im using only simple commands.run because vscode doesnt have support out of the box for running more than command for some mysterious reason. Can you also *please* add completions for commands inside command.run args (i can work on it)

**Comment by usernamehw** [comment]
@wdanilo It should work, extension activates on startup and additionally has activation event for this command: https://github.com/usernamehw/vscode-commands/blob/2e5e580098d1228df1aaeb2bed6e7907976ff66c/package.json#L44-L46

Like previous comment: you should check if extension installed and activated. Possible to see with `workbench.action.showRuntimeExtensions` Title **Developer: Show Running Extensions** 

Maybe there are errors in devtools `workbench.action.toggleDevTools` title: **Developer: Toggle Developer Tools**?

**Comment by usernamehw** [comment]
@zardoy Contribution point is kind of bloated because VSCode doesn't support referencing in json schema for configuration:https://github.com/usernamehw/vscode-commands/blob/2e5e580098d1228df1aaeb2bed6e7907976ff66c/package.json#L61-L846 - Things are duplicated like 8 times. Do you want autocomplete only for properties that have autocomplete or for all? It won't work for things like extension contributed things, unlike `commands.suggestCommands` command.

**Comment by usernamehw** [comment]
@zardoy I'll try to make a web version next week. It's possible to do it without codespaces, right?

**Comment by zardoy** [comment]
> It's possible to do it without codespaces account, right?

Of course, simplest way: https://vscode.dev (I'm actually using it sometimes for repros, as opening new incognito tab is faster than installing/updating Insiders). I remember vscode folks were forcing vscode.dev and `.` GitHub keybinding for a like 8 months

**Comment by wdanilo** [comment]
@usernamehw hmm, it still does not work for me. What I've checked:

1. `Developer: Show Running Extensions` - I can see "Commands 1.4.3" running with caption "Activation: 6ms".
2. I restarted the IDE after installed the extension (full restart).
3. In the dev console I see only "𝗙𝘂𝗻𝗱𝗿𝗮𝗶𝘀𝗶𝗻𝗴 𝗔𝗻𝗻𝗼𝘂𝗻𝗰𝗲𝗺𝗲𝗻𝘁" but not errors.

Btw, I'm running M2 MacOS, but I hope it does not affect it.

**Comment by usernamehw** [comment]
@wdanilo Yeah, that's not the right, version is **1.6.0**. Hashtag #notMyExtension...

<img width="400" src="https://user-images.githubusercontent.com/9638156/216246666-9cccd85b-a7d6-4e62-aca3-090d78e4115f.png">

**Comment by wdanilo** [comment]
Oh wow, this was so confusing. Damn. They should not allow for multiple extensions with the same name. Thank you!
