### ISSUE TITLE
Extension conflicts with another extension by the same name

### ISSUE THREAD

**Issue by jhillert-dmg** [usernamehw/vscode-commands#21]
For a long time, I have used this extension to customize my statusbar:
https://github.com/fabiospampinato/vscode-commands

The problem is your extension uses the exact same name, "vscode-commands", and the exact same identifier in the vs-code settings.json file, "commands.commands".  I want to use both extensions so I can add commands to my sidebar and to the statusbar.  Can you please rename so the two do not conflict with one another in settings.json.  I am asking you because the other extension has more downloads and is several years older.  

Alternatively, maybe you and the other developer can merge your extensions into one.  That would be super cool and make your efforts and the other developers extension a lot more popular.  It would probably be the most powerful extension for modifying vs-code UI in the whole marketplace.

**Comment by usernamehw** [comment]
Nope, not interested in renaming or merging. Sorry.

**Comment by GitMensch** [comment]
@jhillert-dmg But the good new is: this extension has support for statusbar, too - maybe you migrate your statusbar setup to this extension? If not: Is there something missing here concerning the statusbar?

**Comment by jhillert-dmg** [comment]
Ok, so:
1. I am a little confused about the statusbar support.  Did your VS Code Marketplace documentation always say it supported statusbar.  There seems to be a lot more here than the last time I checked, but maybe I just was not paying attention.
2. I will try out the suggested migration and tell you how it goes (i.e., complain if it doesn't go well).
3. While I have your attention... if there is any way to customize this bar down the road, that would be awesome.  It is the most valuable real estate on the screen, and I haven't found any extensions that allow customization.
![image](https://user-images.githubusercontent.com/85570613/151043682-bbd69e70-bc62-4f75-bfad-5b398e389599.png)

**Comment by jhillert-dmg** [comment]
Got it.  re item 3
re 1-2, thanks for doing this.  the flexibility and customization the extension provides is awesome.

**Comment by GitMensch** [comment]
Totally, thanks go out to @usernamehw and contributors (I'm just one of these).

**Comment by jhillert-dmg** [comment]
haha, did you see usernamehw's response above?  But fine, glad you all just made the best editor even better: so thank you usernamehw,
