### ISSUE TITLE
FR command in editor menu bar

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#26]
With commands in Tree View / Status Bar / Quick Pick this extension has all places covered but the editor menu bar.
Please add this, allowing all command configuration be done with this extension.

There's a "kind of hard-wired" extension that does this single thing quite well so the general idea can be seen there https://open-vsx.org/extension/jerrygoyal/shortcut-menu-bar (the code can't be copied because it is GPL, but the public vscode API would be accessed the same way).

The configuration here would be similar to the Status Bar implementation (own sub-configuration and a "Toggle Editor Menu Bar" context menu entry to add/remove it).

**Comment by usernamehw** [comment]
The api is not flexible enough. It's going to require editing of `package.json` file, like the `commands.populateCommandPalette` setting.

Looking at open issues of that extension:

- Would require editor reload for using fully custom items (using predefined actions is not great)
- VSCode hides icons under a `...`
- Not possible to reorder items

And I personally don't like icons there (to the point of using Custom CSS extension to always hide them).

**Comment by GitMensch** [comment]
> The api is not flexible enough. It's going to require editing of `package.json` file, like the `commands.populateCommandPalette` setting.

Agreed. I've actually found that hack quite cool btw. Was it your idea or copied from somewhere else?

> and I personally don't like icons there 

So I guess you may not implement it but would agree to work together on a PR to make this work and then integrated? Note: the reorder should be possible with the package.json hack, too.

**Comment by usernamehw** [comment]
> Was it your idea or copied from somewhere else?

Most likely not mine. Not sure where it's from.

---

Yes, you can work on it. It would be great to use only built-in icons (codicons) and without any predefined actions.

**Comment by usernamehw** [comment]
No plans for this.
