### ISSUE TITLE
FR: adjust to make available as web extension

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#27]
Currently this extension cannot be activated at all, I suggest to add the additional web-extension entry points and make a subset of the features available (I think most should work as-is).

Details can be found at https://code.visualstudio.com/api/extension-guides/web-extensions.

**Comment by usernamehw** [comment]
@zardoy you can try it on the web now.

**Comment by zardoy** [comment]
> @zardoy you can try it on the web now.

This is really good, I'm happy with this! Now I think its by far best extension for commands thx!
