### ISSUE TITLE
Missing name in the status bar context menu

### ISSUE THREAD

**Issue by Z-E-D** [usernamehw/vscode-commands#28]
I just discovered this extension and I like it. One thing that I cannot find is how to get displayed the name of the command in the context menu of status bar. The[ statusbar_commands](https://marketplace.visualstudio.com/items?itemName=anweber.statusbar-commands) extension that I am using right now has that option.

Here is what I am trying:
```
    "commands.commands": {
        "Save Without Formatting": {
            //"command": "workbench.action.files.saveWithoutFormatting",
            "statusBar": {
                "alignment": "left",
                "text": "$(save)",
                "tooltip": "Save Without Formatting (Ctrl+K Ctrl+Shift+S)",
                "priority": -9999,
                "color": "#00ffff",
            },
            "sequence": [
                "workbench.action.files.saveWithoutFormatting",
                "workbench.action.focusActiveEditorGroup"
            ]
        }
    },
```

When I right click on the status bar I see the item for that command in it, but with the empty name. It would be nice if your extension has additional settings for that (it is called "name" in the mentioned other extension), or you could just use the same text that is specified for that command. I tried adding:
`"commands.statusBarDefaultText": "same",`
but I don't see that anything changed.

By the way, your extension also has the problem with the focus that I reported [recently](https://github.com/microsoft/vscode/issues/145432), which is why I have added "workbench.action.focusActiveEditorGroup" to the "sequence".

**Comment by usernamehw** [comment]
Not giving focus to the editor is most likely a VSCode design choice.

Created an issue of VSCode not rendering codicon resulting in an empty menu item: https://github.com/microsoft/vscode/issues/145480

Added a `"name"` property for status bar items. Added a prefix `Commands: ` to the context menu.

**Comment by Z-E-D** [comment]
Thanks for the update.

I don't think that not giving back focus to the editor is most likely a VSCode design choice:
1. as I mentioned in the report, there are commands invoked from the statusbar that don't take focus from the editor, e.g. Undo or Go Back;
2. the commands that are taking the focus when invoked from the statusbar don't do that when they are invoked:
 a) from the menu using the native menu item;
 b) from the toolbar using buttons created by extensions with the same command, e.g. the Save button from [ShortcutMenuBar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar) extension doesn't take the focus.

**Comment by usernamehw** [comment]
> On other side, there are some commands that are not stealing the focus from editor, like these:
> - "Undo" / "Redo",
> - "Go Back" / "Go Forward",
> - "Go to Last Edit Location",
> - "Toggle Split Editor in Group",
> ...

It's possible that these commands just focus the active editor internally unlike other commands.

**Comment by Z-E-D** [comment]
That is inconsistent and unneeded behavior.

And why the Save command give focus back to the editor when invoked from the menu or toolbar, but not the same command when invoked from the statusbar? This is also inconsistent.

**Comment by Z-E-D** [comment]
I just tried. The Save command when executed from the side panel created by your extension is also not giving back the focus to the editor.

**Comment by usernamehw** [comment]
I honestly think that the best feature of this extension is running commands from the Quick Pick.

`commands.openAsQuickPick` - **Commands: Open as Quick Pick**

It would likely return the focus to editor in all cases bc Quick Pick closes when it runs the command.

https://github.com/usernamehw/vscode-commands#quick-pick-commandsopenasquickpick
