### ISSUE TITLE
Show user-facing error notification when running command fails

### ISSUE THREAD

**Issue by megamorphg** [usernamehw/vscode-commands#32]
I tried to setup the following sequence as per the example:
```
"DefaultTabsInGroups": {
            "sequence": [
                {
                    "command": "workbench.action. focusFirstEditorGroup",
                },
                {
                    "command": "commands.openFolder",
                    "args": "O:\\main.md",
                },
            ],
        },
```

But when I run it, it does not execute anything.

The "simple" syntax without declaring the command object in your example **does** work though, though there is no way to enter arguments that way (and be able to open the file as in the 2nd step in my sequence above).

Is my formatting incorrect? Is comma-separation not required inside and outside the bracket? The example's image and text syntax did not match and had different syntaxes so it was confusing.

**Comment by usernamehw** [comment]
Console shows:

> ERR command 'workbench.action. focusFirstEditorGroup' not found: Error: command 'workbench.action. focusFirstEditorGroup' not found

So you have extra space in the command name.

Still, it would be better if extension showed errors to the user when running command fails.
