### ISSUE TITLE
Path related variables would cause JSON parse errors on Windows due to backslash

### ISSUE THREAD

**Issue by ParticleG** [usernamehw/vscode-commands#33]
Using `${fileDirname}` or other path related variables on Windows would result in a JSON parse error.
eg:
```Json
"commands.commands": {
  "list files": {
    "command": "commands.runInTerminal",
    "args": "ls -l ${fileDirname}"
  }
}
```

**Comment by usernamehw** [comment]
Cannot reproduce. It this like a WSL issue?

**Comment by ParticleG** [comment]
Nervermind, can't reproduce this one weeak later.

**Comment by ParticleG** [comment]
Okay, I reproduced that.
If using `"args":{"text":"command"}` syntax, it would cause a JSON parse error. Simply pass command to `args` works fine.
```json
"commands.commands": {
  "list files": {
    "command": "commands.runInTerminal",
    "args": {
      "text": "cp ${file} C:\\Windows\\Temp\\${fileBasename}.log"
    }
  }
}
```
