### ISSUE TITLE
Can you please lower vscode dependency?

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#34]
@usernamehw It _seems_ that the vscode engine version in pacakge.json was only increased as part of a dependency update - but this means that the current version only works with the noted minimal version.

To support "legacy" environments it would be nice to support older versions, an you please drop that to `1.55`? If it still builds fine afterwards then it should also run fine (the current last working version with that dependency was 0.0.6).

... and with the current bugfixes this could even get in the soon upcoming version :-)

**Comment by usernamehw** [comment]
Nope. Not interested. **1.66** is half-year old. Recommended version is always latest (**1.71** now).

Did VSCode increase minimum system requirements from **1.55**? What's the point on using the old version?

**Comment by GitMensch** [comment]
> Did VSCode increase minimum system requirements from 1.55?

vscode not, but "Visual Studio Code" increased requirements and kicked out a bunch of previously supported environments (which work in VSCodium btw).

> What's the point on using the old version?

Apart of the increased requirements: "legacy" environments. As a user I follow the recommendation on using always the latest one, in corporate environments this is often not the case:
An upgrade needs full regression tests, is not done that often, different behavior is not always easy to be accepted (I'm still looking for the option to not have to tell a lot devs that when they open one of the many internal, trusted workspaces, after the upgrade they have to set the trust once - for each), ... .

**Comment by GitMensch** [comment]
Thank you very much, I'll test on a 1.55 as soon as there is a release.
(as checked with the error-lens extension its minimal version may be set to 1.59)
