### ISSUE TITLE
Feature request: filter by editor's language

### ISSUE THREAD

**Issue by NekoiNemo** [usernamehw/vscode-commands#36]
Please add ability to filter by active editor's language for status bar items, rather than just `activeEditorGlob`, to define actions specific to a language.

It's currently possible to do a workaround by filtering on extension using `activeEditorGlob` but it's a rather inconvenient hack to achieve this functionality.

**Comment by usernamehw** [comment]
```
activeEditorLanguage?: string;
```

If status bar item has both `activeEditorLanguage` & `activeEditorGlob` – glob property will take priority.
