### ISSUE TITLE
Glob issue

### ISSUE THREAD

**Issue by NekoiNemo** [usernamehw/vscode-commands#37]
Glob doesn't seem to parse the "one of" matchers correctly. For example string `**/*.@(scala|sbt)` (and same with *, !, +) is supposed to match files
```
/foo/bar/test.scala
/foo/bar/test.sbt
```
(https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.%40%28scala%7Csbt%29&matches=false&tests=%2Ffoo%2Fbar%2Ftest.scala&tests=%2Ffoo%2Fbar%2Ftest.sbt)

However it does not. Using pattern without the "one of" group like `**/*.scala` works fine.

Commands: `V.1.4.0`
VSCode:
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.9-arch1-1
Sandboxed: No
```

**Comment by usernamehw** [comment]
Maybe VSCode glob matching works differently? https://code.visualstudio.com/api/references/vscode-api#GlobPattern

**Comment by NekoiNemo** [comment]
Thank you!
Yep, my bad, i didn't suspect VSCode would have their own globbing pattern. Sorry for the inconvenience

**Comment by NekoiNemo** [comment]
Though i guess it's worth noting that the context help for the `activeEditorGlob` links to this [npm package](https://github.com/isaacs/node-glob#glob-primer) that does use syntax i described. Maybe it should be relinked to the VSCode's own glob syntax from the above
