### ISSUE TITLE
command configuration cannot be stored in workspace files

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#38]
Version 0.0.6 - commands defined in .code-workspace (because they depend on the workspace) work fine
Version 1.5.0 (presumably also some versions before): the configured commands are ignored, checking the problem pane in the workspace configuration shows that `commands.commands` now have an application scope and can only be set in the user configuration.

@usernamehw: is there any option to roll that back? Maybe it would be possible to say "it can be workspace configured but those settings are only read if there's enabled workspace trust".

**Comment by usernamehw** [comment]
What's the goal of storing settings in `.code-workspace` file: to use workspace config or to exclude file from source control? 

Between these 2 versions new setting was created `commands.workspaceCommands`. No plans to change anything.

**Comment by GitMensch** [comment]
The purpose is to store the setting in the .code-worksapce - _included_ in source control.
`commands.workspaceCommands` sounds like the way to go, thank you very much!
