### ISSUE TITLE
“commands.commands” setting expects array instead of object

### ISSUE THREAD

**Issue by manojbaishya** [usernamehw/vscode-commands#39]
![image](https://user-images.githubusercontent.com/28330014/197449871-c45efe5e-a0a1-4144-b7aa-60b0e9c5f752.png)

**Comment by usernamehw** [comment]
Cannot reproduce. Which version VSCode & Commands extension? Also paste setting value as text.

**Comment by usernamehw** [comment]
Also, it's possible that you have [fabiospampinato.vscode-commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) installed alongside.

**Comment by manojbaishya** [comment]
You are right! [fabiospampinato.vscode-commands](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-commands) was installed, removed it and the error is now gone, thanks.

![image](https://user-images.githubusercontent.com/28330014/197479168-979c73d8-ca9b-4c26-ae40-9fe7fabbabb4.png)
