### ISSUE TITLE
"Unable to write to Workspace Settings because my.workspaceColor is not a registered configuration." / ability to access nested settings

### ISSUE THREAD

**Issue by frypf** [usernamehw/vscode-commands#42]
I was experimenting with the ideas discussed in #25, ie. using custom config settings to pass as variables to other commands (eg. `${config:my.workspaceColor}`). I've realised that while this works if I've added it to the json manually, it's impossible at the moment to add or update it via the extension - eg. the following sequence fails with the above notification:
```
{
  "sequence": [
    {
      "command": "commands.toggleSetting",
      "args": {
        "setting": "my.workspaceColor",
        "target": "workspace",
        "value": [ "#00f00f33" ]
      }
    },
    {
      "command": "commands.toggleSetting",
      "args": {
        "setting": "workbench.colorCustomizations",
        "target": "workspace",
        "value": [ {
            "statusBar.background": "${config:my.workspaceColor}",
            "titleBar.activeBackground": "${config:my.workspaceColor}",
            "tab.activeBackground": "${config:my.workspaceColor}",
            "sideBar.background": "${config:my.workspaceColor}"
          } ]
      }
    }
  ]
}
```
Is there any way to force an unknown configuration into settings? The second part of that sequence works as intended on its own, correctly reading the value of a manually-set `my.workspaceColor` into the specified settings. I also noticed the extension doesn't complain if I add my unknown config into a nested object. Thus, as an alternative I attempted:
```
{
  "sequence": [
    {
      "command": "commands.toggleSetting",
      "setting": "workbench.colorCustomizations",
      "target": "workspace",
      "value": [ { "my.workspaceColor": "#00f00f33" } ]
    },
    {
      "command": "commands.toggleSetting",
      "args": {
        "setting": "workbench.colorCustomizations",
        "target": "workspace",
        "value": [ {
            "statusBar.background": "${config:workbench.colorCustomizations['my.workspaceColor']}",
            "titleBar.activeBackground": "${config:workbench.colorCustomizations['my.workspaceColor']}",
            "tab.activeBackground": "${config:workbench.colorCustomizations['my.workspaceColor']}",
            "sideBar.background": "${config:workbench.colorCustomizations['my.workspaceColor']}"
          } ]
      }
    }
  ]
},
```
However I then realised it's not possible to grab a nested value from a `${config:...}` variable (I'd also initially tried `${config:workbench.colorCustomizations.my.workspaceColor}`). Is there any syntax available to access such nested settings?

PS: I was originally investigating all this as a workaround for using shell command substitutions as variables. If there was any way to read a command substitution directly into a variable - or even just access the current clipboard OR content from a specified tempfile OR environment variables from an open terminal, I could greatly simplify this or similar sequences by initially using a `runInTerminal` command to set clipboard via pbcopy / write said tempfile / export said env var. Albeit I don't know enough about TS and the available VSCode APIs to get a feel for how feasible or difficult any of that may prove to implement.

**Comment by usernamehw** [comment]
No, it doesn't work with nested configuration in that way or maybe it's a `workbench.colorCustomizations` problem? I don't know.

Have you tried to use [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) or [Profiles](https://code.visualstudio.com/updates/v1_75#_profiles) for this task?

**Comment by usernamehw** [comment]
You can create an empty extension to register the `my.workspaceColor` configuration. Then the update function (at least for that setting) would work.

**Comment by usernamehw** [comment]
> PS: I was originally investigating all this as a workaround for using shell command substitutions as variables. If there was any way to read a command substitution directly into a variable - or even just access the current clipboard OR content from a specified tempfile OR environment variables from an open terminal, I could greatly simplify this or similar sequences by initially using a `runInTerminal` command to set clipboard via pbcopy / write said tempfile / export said env var. Albeit I don't know enough about TS and the available VSCode APIs to get a feel for how feasible or difficult any of that may prove to implement.

Could you provide a clearer example of what you're trying to achieve?

**Comment by usernamehw** [comment]
> I'm guessing these have to be declared in the manifest rather than dynamically?

Yes, all the items in menus and command palette and settings, they are all static: https://github.com/usernamehw/vscode-commands/blob/7a13e71321e2e2907dcd7664bf00bb078e928acf/package.json#L57-L67

**Comment by usernamehw** [comment]
Maybe it would be easier for you to create an extension (not an empty one) with the intended logic?

**Comment by frypf** [comment]
I may end up doing so, or just cludging together something with jq on the command line if I can figure out a way around any json comments and trailing commas without stripping them altogether. Or actually maybe just writing a tempfile with the command result, setting the appropriate settings to some temporary placeholder value and then running another `runInTerminal` to replace that value via sed might be simpler - your empty extension idea has got me thinking of just using a temporary-type ${config:...} variable as a means to store something quickly for the duration of a command sequence. Would there be any scope for adding such a temp variable(s) to this extension? I can only envisage needing 1 in this case as I'd then empty it after use at the end of a sequence, although maybe you can see a more generalised use case for having more available?

I remember a while back I tried to get my head around using a command substitution as a variable for something else after reading https://code.visualstudio.com/docs/editor/variables-reference#_command-variables, but came to the conclusion it wasn't possible, or at the very least not simple. I was just wondering again today if there was any way of harnessing the flexibility of your extension to take out the middle man, so-to-speak.

**Comment by frypf** [comment]
Think I managed to work it out in the end - took a while to figure out the quoting to keep the workspace json nicely formatted but still allow easy undoing in minimal steps. Thanks for pointing me in the right direction:
```
"cmd.workspace.randomColor ": {
  "sequence": [
    {
      "command": "commands.runInTerminal",
      "args": {
        "text": " pastel random -n 1 -s rgb | pastel format hex >| '/tmp/VSCODE_TEMP_VAR'",
        "name": "cmd.workspace.randomColor"
      }
    },
    {
      "command": "commands.toggleSetting",
      "args": {
        "setting": "workbench.colorCustomizations",
        "target": "workspace",
        "value": [ "<<VSCODE_TEMP_VAR>>" ]
      }
    },
    {
      "command": "workbench.action.terminal.sendSequence",
      "args": {
        "text": " vscode_temp_var=\"$( cat '/tmp/VSCODE_TEMP_VAR' )\" && col_cust=\"{\\n\\t\\t\\t\\\"statusBar.background\\\":\\\"${vscode_temp_var}33\\\",\\n\\t\\t\\t\\\"titleBar.activeBackground\\\":\\\"${vscode_temp_var}33\\\",\\n\\t\\t\\t\\\"tab.activeBackground\\\":\\\"${vscode_temp_var}33\\\",\\n\\t\\t\\t\\\"sideBar.background\\\":\\\"${vscode_temp_var}33\\\"\\n\\t\\t\\t}\" && sed -i '' -e \"s/\\\"<<VSCODE_TEMP_VAR>>\\\"/${col_cust}/\" '${file}' ; rm '/tmp/VSCODE_TEMP_VAR'; exit\n"
      }
    },
  ],
  "when": "editorFocus && resourceExtname == .code-workspace"
}```

**Comment by usernamehw** [comment]
Would it be easier if variable substitution supported clipboard value? It's possible to do with vscode api.

**Comment by frypf** [comment]
Ooh, actually yes that would probably help a lot. The sequence I posted above does work, albeit it's a bit janky & slow. If I could access the clipboard directly, it'd just be a matter of piping the initial shell command into pbcopy and then I could hopefully bypass the placeholder value and extra `terminal.sendSequence` sed call altogether. It would also potentially simplify any other use cases where I need to pass in a shell result. Thanks for your help mate, I appreciate this kind of functionality is probably not what you'd originally envisaged, but as I said before your extension has come in truly useful in some fairly varied and unexpected situations.

**Comment by frypf** [comment]
> No, it doesn't work with nested configuration in that way

Just to revisit accessing settings within nested objects again, is this a VSCode API limitation or would it be possible to return such objects/arrays as a stringified JSON? We could then parse out the required part(s) ourselves in the shell via jq or sed or similar.

**Comment by usernamehw** [comment]
> Just to revisit accessing settings within nested objects again, is this a VSCode API limitation or would it be possible to return such objects/arrays as a stringified JSON?

Right now it only replaces if the value is of type `string` or `number` (not vscode limitation). I would need to change the code to return stringified value if it's an array or an object.

**Comment by frypf** [comment]
Ah I see, just had a quick look at [substituteVariables.ts](https://github.com/usernamehw/vscode-commands/blob/f8ffbd0b2b87de66625cc0ddc190b7cce87671e4/src/substituteVariables.ts). Would there be any scope for adding additional recursion in there for config-type variables if a property key were given in square brackets, failing with a similar notification if no such key was given? Or would that require too much refactoring / break functionality elsewhere? If it's feasible, between that and the proposed clipboard access as a variable, it would allow for some seriously granular access to and control over individual sub-settings more generally.

**Comment by usernamehw** [comment]
Clipboard is relatively easy to do 6925d40e1b91b87a22d44fd8223d2df5091d0ec0. 
Returning stringified objects/arrays should be too. 

Walking recursively for settings - no plans.

**Comment by frypf** [comment]
I figured that wouldn't make for a simple change, although tbh even accessing a stringified representation would still allow for some awesome new possibilities. Looking forward to trying out the clipboard functionality once the marketplace picks up the latest commit, thanks again!

**Comment by frypf** [comment]
Oh, apologies for nagging with multiple (albeit hopefully related) requests, but I've just noticed config retrieval also fails for boolean/undefined values - is it possible to account for those as a simple true|false|null?

**Comment by usernamehw** [comment]
Closing.

**Comment by frypf** [comment]
Thanks for this, I've tested it a bit and it's definitely a lot smoother than previously.

Unfortunately I've noticed an issue: when I actually come to use `${clipboard}` within `toggleSetting` it only ever populates with the value of the clipboard as it was at the last window reload (or the last time I made some change to the `cmd.workspace.randomColor` command/sequence itself within my settings json). I've added a couple of checks to the following sequence just to try to see what was going on:
```
"cmd.workspace.randomColor ": {
  "sequence": [
    {
      "command": "commands.runInTerminal",
      "args": {
        "text": " pastel random -n 1 -s rgb | pastel format hex | tr -d '\\n' | pbcopy; printf -- '%s\\n' '${clipboard}' >>| vsc_cmd_cb_test",
        // "text": " printf -- '#%s' $( LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 6 ) | pbcopy; printf -- '${clipboard}\n' >> cb_test",
        "name": "cmd.workspace.randomColor",
        "reveal": true
      }
    },
    {
      "command": "commands.showStatusBarNotification",
      "args": { "timeout": 2500, "message": "${clipboard}" },
    },
    {
      "command": "commands.toggleSetting",
      "args": {
        "setting": "workbench.colorCustomizations",
        "target": "workspace",
        "value": [ {
            "statusBar.background": "${clipboard}33",
            "titleBar.activeBackground": "${clipboard}33",
            "tab.activeBackground": "${clipboard}33",
            "sideBar.background": "${clipboard}33",
          } ]
      }
    },
  ],
  "when": "editorFocus && resourceExtname == .code-workspace"
},
```
The `${clipboard}` var is definitely being updated by the initial `runInTerminal` piping into pbcopy, and the extension is definitely seeing the updated value. Both the `vsc_cmd_cb_test` file & the `showStatusMessage` correctly show the updated value, but for whatever reason, the setting itself never receives anything other than the old value. Any idea what might be going on here?

**Comment by frypf** [comment]
Actually I've just noticed that sometimes the workspace just turns bright red (I'm guessing #ff0000 is a fallback value if VSCode can't interpret the given string as a colour). This happens when I have some other string already in the clipboard at the time I reload the window or change the command in settings, which is what then gets populated. It's like it's evaluating `${clipboard}` at the time the extension loads, but only when used in `toggleSetting` - everything else seems to interpret it at the time of invocation 🤔.

**Comment by usernamehw** [comment]
You can try a new version. Change `.zip` to `.vsix` & install from vsix [commands-1.8.0.zip](https://github.com/usernamehw/vscode-commands/files/10774479/commands-1.8.0.zip)

**Comment by frypf** [comment]
Seems to have done the trick thanks, it's evaluating correctly now. Is there any way around the timing issue beyond hardcoding a delay into the command where I use the clipboard? Maybe a way to make `runInTerminal` optionally await completion via a non-default option within the JSON?

I saw in the API docs it does seem possible to get an `exitStatus` back from a terminal once it's closed. Maybe if the `runInTerminal` was specified with eg. `"waitForCompletion": true`, then append an `"\n exit $?"` to its text to make sure it closes itself once done and return a promise which resolves or rejects according to said `exitStatus`?

**Comment by usernamehw** [comment]
Makes sense. You can try `"waitForExit": true` in [commands-1.8.0.zip](https://github.com/usernamehw/vscode-commands/files/10774881/commands-1.8.0.zip)

**Comment by frypf** [comment]
Well that was a quick turnaround - works perfect thanks again 👍
