### ISSUE TITLE
autocomplete does not work in settings.json within `commands.commands`

### ISSUE THREAD

**Issue by GitMensch** [usernamehw/vscode-commands#43]
The "reveal in settings.json" command works fine, but with v 1.8.0 there is no auto-complete / syntax-check so it is easy to be lost and fail into typos.
There were some recent commits that sound like they may fix this, but I don't know.

**Comment by usernamehw** [comment]
Recent commits are minor fixes to autocomplete.

I need a minimal sample to reproduce.

**Comment by usernamehw** [comment]
Cannot reproduce. Example **1.8.0** on the web (almost empty config):

![Animation](https://user-images.githubusercontent.com/9638156/220107150-432662bb-da93-47ad-82e0-c0c27b69ae32.gif)

**Comment by GitMensch** [comment]
That's exactly how it should be...

Rechecked: It works that way when opening a plain vscode, but doesn't when working on a remote connection...
autocomplete for `"commands."` (the settings) works fine in both cases; but as soon as connecting to a remote workspace the commands itself don't have it...

Any idea?

**Comment by usernamehw** [comment]
I don't use remote and don't know the difference. Do you think it's the right thing to run this extension in `workspace` instead of `ui`?

**Comment by GitMensch** [comment]
> I don't use remote and don't know the difference. Do you think it's the right thing to run this extension in `workspace` instead of `ui`?

@jeanp413 @daiyam Can you help here with knowledge and/or useful documentation?

**Comment by daiyam** [comment]
Remote extensions can be tricky...
I think the extension should only be `ui` (the call of the commands is done on the client)

```jsonc
"remote.extensionKind": {
	"usernamehw.commands": [
		"ui",
	],
},
```

**Comment by jeanp413** [comment]
So if I'm not mistaken autocompletion comes from the json scheme, so probably the json language server extension is not applying the schema contributed by this extension for some reason :thinking: 

@usernamehw  Maybe test if instead of  [`"fileMatch": "**/settings.json"` ](https://github.com/usernamehw/vscode-commands/blob/f1a1b477a17143e607afafd587d22fff42101b88/package.json#L341) using [`"fileMatch": "%APP_SETTINGS_HOME%/settings.json"`
](https://github.com/microsoft/vscode/blob/2e1c8053c0ff9bd5e7cf311ffcfe3c21f15ccde8/extensions/configuration-editing/package.json#L86-L93)  works ? (`%APP_SETTINGS_HOME%` will be replaced by the json langauge server extension internally)

**Comment by usernamehw** [comment]
Thanks.

This `"fileMatch": "%APP_SETTINGS_HOME%/settings.json"` fails to target workspace settings file.

I think it might be because of cross file references: https://github.com/usernamehw/vscode-commands/blob/f1a1b477a17143e607afafd587d22fff42101b88/data/settings.schema.json#L140

**Comment by usernamehw** [comment]
@GitMensch  could you test this version (as a UI extension): [commands-1.8.0.zip](https://github.com/usernamehw/vscode-commands/files/10790464/commands-1.8.0.zip)

**Comment by GitMensch** [comment]
I've tried both: download, rename .zip to .vsix, install from vsix... - and before removed the entry in settings.ui.

The first one led to the extension to not be visible at all, the second one was visible again, but the issue persists.

Then got back to the visx from open-vsx.
Using only "ui" in the setting and reloading led to a disabled extension.
Using only "workspace" leads to a locally disabled extension, but with request to install that on the remote - and as soon as this was done the extension worked again; and this time the auto-complete also works with an active remote.

Conclusion: it should be enough to only request "workspace". I'm here to retest a 1.8.1.vsix that has that option, if you want me to.

**Comment by usernamehw** [comment]
It should work in the latest version where "workspace" is the preferred kind:

https://github.com/usernamehw/vscode-commands/blob/32c49c9f79834b925e46d99d149b1167745aea3d/package.json#L11-L14
