### ISSUE TITLE
Implement when clause for Quick Pick

### ISSUE THREAD

**Issue by depascalis** [usernamehw/vscode-commands#49]
I'm uncertain if the Extension API supports this, so I'm creating this to track eventual blocking issues if not.

I really like the idea of using the when clause for commands. Personally however I don't see much benefit of enabling it for the Command Palette, it would be awesome if it could be implemented for the Quick Pick though.

The use case is that I would like to make the Quick Pick completely context based. Imagine opening the Quick Pick and only see your choice of commands, and only see commands relative to the context from which it was opened, what a wonderful world.

_I was researching for achieving this with the RMB Context Menu, but there are too many issues blocking this atm._

Related PR #22 
Ping @elazarcoh

**Comment by elazarcoh** [comment]
I think it's blocked by https://github.com/microsoft/vscode/issues/10471

**Comment by usernamehw** [comment]
Yeah, that issue is 7 years old now. And Pull Request https://github.com/microsoft/vscode/pull/118722 to fix it was closed.

**Comment by usernamehw** [comment]
Closing as there's no api.
