### ISSUE TITLE
argument as popup input box

### ISSUE THREAD

**Issue by renadmunna** [usernamehw/vscode-commands#52]
it will be very helpful if I can input some custom text as part of the command code.
for example,
echo ${agrument}
it will pop up an input box to take the argument value.

**Comment by usernamehw** [comment]
That would be a task `Input variables` in the existing issue #9. Closing as duplicate.

**Comment by renadmunna** [comment]
Can it be instant input-taking with an input box, not selected text? sometimes it is helpful to input multiple arguments as instantly. for example: npx cap add android
it will be like this: npx cap ${arg1_label} ${arg2_label}
compiled as: for ${arg1_label} a input box will be popup to take the input. arg1_label will be shown as plasceholder or tile of the input box... 
https://github.com/deepakg202/vscode-save-commands
this extension has this feature. pls review that for example.
but your extension has a great feature to categorise the commands and grope them.

**Comment by usernamehw** [comment]
That sounds exactly what `Input variables` is in #9 issue. An equivalent of https://code.visualstudio.com/docs/editor/variables-reference#_input-variables and not implemented yet; That's why that task is not checked and that issue is not closed.
