### ISSUE TITLE
Issue : This setting has an application scope and can be set only in the user settings file.

### ISSUE THREAD

**Issue by laurent512** [usernamehw/vscode-commands#55]
Hi , 

Thanks for the nice addon ! 
Is there a way to define the commands for the project at the workspace level? 

I am confronted to this error below  when I define the commands inside the root>.vscode>.settings.json file  : 
This setting has an application scope and can be set only in the user settings file.

Thank you :)

**Comment by usernamehw** [comment]
Workspace commands use different setting:

```js
"commands.workspaceCommands": {
	// ...
},
```

**Comment by laurent512** [comment]
Thank you ! it is working ! 
Do you know if there is a way to create a command that would run in sequence commands that have been already defined ? ( by referencing them) ?

**Comment by laurent512** [comment]
It is ok ! Thank you for the great lib ! :) 


   "command": "commands.run",
            "args": [
                {
                    "command": "commandnameA"
                },
                {
                    "command": "commandNameB"
                }
            ],

**Comment by laurent512** [comment]
Now I have no clue why but I have this error when vscode boot :  "Cannot convert undefined or null to object"

This is my setup , everything is working , I would be curious to know if you have the same issue :/
"commands.workspaceCommands": {
        "NPM": {
            "nestedItems": {
                "Run Dev": {
                    "command": "commands.run",
                    "args": [
                        {
                            "command": "workbench.action.terminal.kill",
                            "args": {
                                "name": "NextJS"
                            }
                        },
                        {
                            "command": "commands.runInTerminal",
                            "args": {
                                "text": "infisical run -- npm run dev\r",
                                "name": "NextJS",
                                "reveal": true,
                                "reuse": "newest"
                            }
                        }
                    ],
                    "icon": "run",
                    "iconColor": "charts.green",
                    "statusBar": {
                        "text": "Run Dev",
                        "color": "yellow",
                        "priority": -101
                    }
                },
                "Update": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "npm update\r",
                        "name": "Npm update",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "arrow-circle-up",
                    "iconColor": "terminal.ansiWhite"
                }
            }
        },
        "Prisma": {
            "nestedItems": {
                "Studio": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "infisical run -- npx prisma studio\r",
                        "name": "Prisma Studio",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "iconColor": "charts.green",
                    "icon": "table",
                    "statusBar": {
                        "text": "Studio",
                        "color": "yellow",
                        "priority": -102
                    }
                },
                "DB push": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "infisical run -- npx prisma db push\r",
                        "name": "DB Push",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "iconColor": "charts.green",
                    "icon": "repl",
                    "statusBar": {
                        "text": "DB push",
                        "color": "orange"
                    }
                },
                "Seed": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "name": "Prisma Gen & Seed",
                        "text": "infisical run -- npx prisma db seed\r",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "export"
                },
                "Generate": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "name": "Prisma Gen & Seed",
                        "text": "infisical run -- npx prisma generate\r",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "combine"
                },
                "Force Reset": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "name": "Prisma Gen & Seed",
                        "text": "infisical run -- npx prisma db push --force-reset\r",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "settings-discard"
                }
            }
        },
        "Git": {
            "nestedItems": {
                "Quick Push ": {
                    "command": "commands.run",
                    "args": [
                        {
                            "command": "commands.runInTerminal",
                            "args": {
                                "text": "git add .\r",
                                "name": "Git Commit & Push",
                                "reveal": true,
                                "reuse": "newest"
                            }
                        },
                        {
                            "command": "commands.runInTerminal",
                            "args": {
                                "text": "git commit -am \"automatic push\" \r",
                                "name": "Git Commit & Push",
                                "reveal": true,
                                "reuse": "newest"
                            }
                        },
                        {
                            "command": "commands.runInTerminal",
                            "args": {
                                "text": "git push",
                                "name": "Git Commit & Push",
                                "reveal": true,
                                "reuse": "newest"
                            }
                        }
                    ],
                    "iconColor": "charts.green",
                    "icon": "rocket",
                    "statusBar": {
                        "text": "Git Quick Push ",
                        "color": "yellow",
                        "priority": -105
                    }
                },
                "Add .": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "git add .\r",
                        "name": "Git Commit & Push",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "gist-new"
                },
                "Commit -am": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "git commit -am \"automatic commit&push\" \r",
                        "name": "Git Commit & Push",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "git-commit"
                },
                "Push": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "git push",
                        "name": "Git Commit & Push",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "run"
                }
            }
        },
        "Stripe ": {
            "nestedItems": {
                "Login": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe login\r",
                        "name": "Stripe",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "log-in"
                },
                "Listen to 3000": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe listen --forward-to localhost:3000/api/stripe/webhook\r",
                        "name": "Stripe",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "ports-forwarded-with-process-icon",
                    "iconColor": "terminal.ansiWhite",

                    "statusBar": {
                        "text": "Stripe Listen to 3000",
                        "color": "orange"
                    }
                },
                "trig : payment_intent succeed": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe trigger payment_intent.succeeded\r",
                        "name": "Stripe Triggers",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "triangle-right"
                },
                "trigg : subscription schedule cancelled": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe trigger subscription_schedule.canceled\r",
                        "name": "Stripe Triggers",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "triangle-right"
                },
                "trigg : invoice upcoming": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe trigger invoice.upcoming\r",
                        "name": "Stripe Triggers",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "triangle-right"
                },
                "trigg : charge captured": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe trigger charge.captured\r",
                        "name": "Stripe Triggers",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "triangle-right"
                },
                "trigg : invoice payment succeeded": {
                    "command": "commands.runInTerminal",
                    "args": {
                        "text": "stripe trigger invoice.payment_succeeded\r",
                        "name": "Stripe Triggers",
                        "reveal": true,
                        "reuse": "newest"
                    },
                    "icon": "triangle-right"
                }
            }
        },
        "Other": {
            "nestedItems": {
                "Reload VScode": {
                    "command": "workbench.action.reloadWindow",
                    "statusBar": {
                        "text": "Refresh Window",
                        "color": "orange"
                    },
                    "icon": "refresh"
                },
                "Kill All Terminal": {
                    "command": "workbench.action.terminal.killAll",
                    "statusBar": {
                        "text": "Kill All ",
                        "color": "red"
                    },
                    "icon": "terminal-kill"
                }
            }
        },
        "Env Setup": {
            "command": "commands.run",
            "args": [
                {
                    "command": "Run Dev"
                },
                {
                    "command": "Studio"
                }
            ],
            "icon": "star",
            "iconColor": "charts.green",
            "statusBar": {
                "text": "Env Setup",
                "backgroundColor": "warning",
                "priority": -100
            }
        }
    }
