### ISSUE TITLE
nested commands with the same name

### ISSUE THREAD

**Issue by tasiotas** [usernamehw/vscode-commands#58]
Hi,

I have a nested items with the structure as show on the screenshot.
Would it be possible to prefix command name with the folder name before registering command in vscode?

If I use the same name, I get error `Failed to register command: command 'caddy' already exists`

![image](https://github.com/usernamehw/vscode-commands/assets/9046931/924ee649-bb1e-4510-b200-84859d064f4b)

thanks!

**Comment by usernamehw** [comment]
I don't want to complicate the code with this.
