### ISSUE TITLE
Problem with the `Reveal in settings.json` button

### ISSUE THREAD

**Issue by parkercode98** [usernamehw/vscode-commands#59]
Hi,

This issue regards the `Reveal in settings.json` button in the status bar tooltip:
![Screenshot-Reveal-Settings](https://github.com/usernamehw/vscode-commands/assets/76987504/eeed5f6a-53f6-486e-bda8-7d3100a41c64)

(Bear with me here as I try to explain VS Code settings)

VS Code recently made **profiles** to save custom settings to an individual profile, which split settings files into 3 types (scopes):
1) **Workspace Settings** - Settings stored inside your workspace
2) **User Settings** - Settings in the current profile that is being used.
3) **Application Settings** - Settings that apply globally.

Note: I'm not sure if this is the default behavior, if you don't opt in to profiles.

Before profiles were introduced, It was just User and Workspace settings (Which might still be the case for people not using profiles). With **User Settings** being the "globally" stored settings.

Anyway, the `commands.commands` setting must be defined in the global scope (the global settings file).
So, when using profiles, `commands.commands` can only be defined in **Application Settings**.
If defined in your **User Settings (Profile Settings)**, It will be grayed out with a message reading: "This setting has an application scope and can be set only in the user settings file." (<- Note that it says "can be set only in the user settings file". By "user settings file" it means Application settings file (¬_¬ )).

All this to say - 
The function below that the `Reveal in settings.json` button calls:
https://github.com/usernamehw/vscode-commands/blob/304360610ea5f6561270e939036c5f0e44c186bc/src/utils/vscodeUtils.ts#L25
```typescript
async function openSettingsJson(target: 'global' | 'workspace'): Promise<void> {
	await commands.executeCommand(target === 'global' ? 'workbench.action.openSettingsJson' : 'workbench.action.openWorkspaceSettingsFile');
}
```
Uses the 'workbench.action.openSettingsJson' command as the 'global' target.
But, when using profiles (or maybe by default now), the global settings file is the **Application Settings** file.
So the global target should be changed to 'workbench.action.openApplicationSettingsJson', and the function should be changed to something like this:
```typescript
async function openSettingsJson(target: 'global' | 'workspace'): Promise<void> {
	await commands.executeCommand(target === 'global' ? 'workbench.action.openApplicationSettingsJson' : 'workbench.action.openWorkspaceSettingsFile');
}
```

Currently, when I click the `Reveal in settings.json` button, it just opens my **User Settings (Profile settings)** without highlighting any label (because there isn't one).

Changing the global target to use 'workbench.action.openApplicationSettingsJson' instead of 'workbench.action.openSettingsJson' fixed the problem for me.

Thanks for all the hard work, this is by far my favorite extension.

**Comment by usernamehw** [comment]
Or are there other things to do? Is `commands.commands` greyed out in profile file and doesn't have autocomplete or something like that?
