### ISSUE TITLE
Exclude file types

### ISSUE THREAD

**Issue by Amanoki** [usernamehw/vscode-commands#61]
Hello, is it possible to exclude file types in activeEditorGlob setting? I have tried:
"!**/*.{md,json}"
"**/*.!{md,txt}"
"**/*.{!md,!txt}"
"{**/*,!**/*.md,!**/*.txt}"
and many variants of ! but they didn't work.
I'm not familiar with glob so not sure if these are the correct patterns.
It would be great if there is a way to exclude file types. 
Thank you!

**Comment by usernamehw** [comment]
https://code.visualstudio.com/docs/editor/glob-patterns

```js
"statusBar": {
	"activeEditorGlob": "**/*[!*.{md,txt}]"
}
```

**Comment by Amanoki** [comment]
Ah, I did read that but didn't know I could put the whole { } inside [ ].
This works perfectly, thank you!
Btw, can activeEditorLanguage support multiple languages or only one? I've tried like "markdown, jsonc" but it worked only when I filled in one language.

**Comment by usernamehw** [comment]
`activeEditorLanguage` only supports 1 language.

**Comment by Amanoki** [comment]
Okay no problem. Thanks for the awesome extension! Please close the issue :)
