### ISSUE TITLE
Show green circle in status bar when `npm run dev` is running, else show grey circle when it's not.

### ISSUE THREAD

**Issue by GorvGoyl** [usernamehw/vscode-commands#65]
I'm not sure if it's possible with this extension, but here's what I want to achieve:

Show a gray circle (or any other icon) in the status bar. If I click on it, it should run the command 'npm run dev' without revealing the terminal and also change the icon to something else (like a green circle) which indicates that the command is actively running. If I click on the green circle, it should stop this running command.

**Comment by usernamehw** [comment]
From the next extension version:

```js
"commands.watchTerminalStatusBar": {
	"enabled": true,
	"defaultText": "💻",
	"successText": " $(gear~spin) ",
	"errorText": "ERROR",
	"sendText": "npm run watch",
	"commandOnClickWhenRunning": "showTerminal",
	"commandOnClick": "commands.startTerminalWatch",
	"errorWhen": [
		"error"
	],
	"tooltipEnabled": true,
	"highlightErrorWithBackground": true,
},
```

![Demo](https://github.com/user-attachments/assets/267fdffd-9b86-4807-9250-b05345c5e5f5)

**Comment by GorvGoyl** [comment]
Thanks. I use Cursor, and unfortunately, the latest version of your extension is not compatible with it. I think Cursor uses a fork of version 1.93.1 of VSCode. Could you make it backward compatible with 1.93.1 if possible?

![screenshot 2024-11-11 at 13 10 04@2x](https://github.com/user-attachments/assets/2159bab5-9b5d-49ba-800d-bbfbf8d7ca23)

![screenshot 2024-11-11 at 13 15 13@2x](https://github.com/user-attachments/assets/3532997a-2f25-442a-8819-38baee58d7b4)

**Comment by usernamehw** [comment]
Since shell integration api was introduced in **1.93.0** it should be possible to downgrade 1 version https://code.visualstudio.com/updates/v1_93#_terminal-shell-integration-api.

**Comment by GorvGoyl** [comment]
Good news is cursor has updated to VSCode Version: `1.93.1` but watchTerminalStatusBar is still not working. I also tested on latest vscode as well just to make sure. When I click on laptop icon I get this error:

![screenshot 2024-11-12 at 13 55 11@2x](https://github.com/user-attachments/assets/79e077c8-1ab4-46db-9449-3b6052296b12)

Device: M1 Macbook Pro
Shell: `zsh`

**Comment by usernamehw** [comment]
Could you try this version (rename `.zip` to `.vsix`):

[commands-1.14.1.zip](https://github.com/user-attachments/files/17714534/commands-1.14.1.zip)

**Comment by GorvGoyl** [comment]
tested it and am facing the same issue. Sometimes it shows that error, and sometimes it opens the terminal window but does nothing.

**Comment by usernamehw** [comment]
I don't know why this happens then. Maybe "shellIntegration" api doesn't support `zsh` yet?

**Comment by usernamehw** [comment]
You have `terminal.integrated.shellIntegration.enabled` setting enabled right?

**Comment by GorvGoyl** [comment]
it is enabled but says 'Shell integration failed to activate'

![screenshot 2024-11-13 at 00 00 45@2x](https://github.com/user-attachments/assets/917d209c-f5f0-451d-ba21-e12681b2454e)

**Comment by usernamehw** [comment]
Well, it needs to be active for this feature to work.

> This standard, easy way will not work for some advanced use cases like in sub-shells, through a regular `ssh` session (when not using the [Remote - SSH extension](https://code.visualstudio.com/docs/remote/ssh)) or for some complex shell setups. The recommended way to enable shell integration for those is [manual installation](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation).

https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation
